### ISSUE TITLE
npm包缺少文件

### ISSUE THREAD

**Issue by jamtanghub** [wshxbqq/node-win-mouse#1]
require模块时报错：
A dynamic link library (DLL) initialization routine failed.↵\?\C:\Users\Tjin\node_modules\node-win-mouse\addon.node   

是不是缺少文件没有上传？

我的使用环境是：操作系统：win10 64bit ，nodejs版本V6.1.0

**Comment by wshxbqq** [comment]
我在 64 bit win10 下 node6.1.0 试了一下.
并没有出现你说的问题.

请检查一下 addon.node 是否出现在指定的位置了.  

如果 -g 安装 . 请检查 NODE_PATH 等环境变量是否配置正确..

**Comment by wshxbqq** [comment]
使用 node-addon-api 重新编译了。 以后不会再存在这个问题了
